name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: cd packages/core && yarn install --frozen-lockfile

      - name: Run build
        run: cd packages/core && yarn build

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x]
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: cd packages/core && yarn install --frozen-lockfile

      - name: Run unit tests
        run: cd packages/core && yarn test
